WorkFlowaMig/Controllers/AgenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PagedList.Mvc;
using PagedList;
using System.Web.Mvc;
using WorkFlowaMig.Models;

namespace WorkFlowaMig.Controllers
{




    public class AgenceController : Controller
    {
        private WorkflowEntities _context;
        public AgenceController()
        {
            _context = new WorkflowEntities();
        }

        //
        // GET: /Agence/
        public ActionResult Index(string search, string sort, int? page)
        {
            IQueryable<Agence> agences = _context.Agences;

            if (!String.IsNullOrWhiteSpace(sort))
            {
                if (sort == "AgenceId_ASC")
                    agences = agences.OrderBy(c => c.Id);
                else if (sort == "AgenceName_DESC")
                    agences = agences.OrderByDescending(c => c.Id);

                else if (sort == "AgenceName_ASC")
                    agences = agences.OrderBy(c => c.Name);
                else if (sort == "AgenceName_DESC")
                    agences = agences.OrderByDescending(c => c.Name);
            }
            else
            {
                agences = agences.OrderByDescending(c => c.Id);
            }
            ViewBag.CurrentSort = sort;

            if (!String.IsNullOrWhiteSpace(search))
            {
                ViewBag.CurrentSearch = search;
                agences = agences.Where(c => c.Name.Contains(search));
            }
            //zones = zones.OrderByDescending(c => c.Id);
            int pageSize = 6;
            int pageNumber = page ?? 1;
            
           
            //ViewBag.ZoneID = new SelectList(_context.Zones, "Id", "Name");
            ViewBag.ZoneId = new SelectList(_context.Zones, "Id", "Name");

            return PartialView(agences.ToPagedList(pageNumber, pageSize));

        }

        public ActionResult GetAgences()
        {
            var _listAgences = _context.Agences.ToList();
            return Json(_listAgences, JsonRequestBehavior.AllowGet); 

        }
        public ActionResult GetAgence(int id)
        {
            var _agence = _context.Agences.Where(u => u.Id == id).FirstOrDefault();
            return Json(_agence, JsonRequestBehavior.AllowGet); 

        }
        public ActionResult AddAgence([Bind(Include = "Id,Code,Name,ZoneId")] Agence agence)
        {
            if(ModelState.IsValid)
            {
                _context.Agences.Add(agence);
                _context.SaveChanges();
            }
            ViewBag.ZoneId = new SelectList(_context.Zones, "Id", "Name", agence.ZoneId);
            return Json(agence, JsonRequestBehavior.AllowGet); 

        }
        public ActionResult UpdateAgence(Agence agence)
        {
            //comment 
            if(ModelState.IsValid)
            {
                _context.Entry(agence).State = System.Data.Entity.EntityState.Modified;
                _context.SaveChanges();
            }
            return Json(agence, JsonRequestBehavior.AllowGet); 
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var agence = _context.Agences.ToList().Find(m => m.Id == id);
            if (agence != null)
            {
                _context.Agences.Remove(agence);
                _context.SaveChanges();
            }

            return Json(agence, JsonRequestBehavior.AllowGet);
        }
	}
}

WorkFlowaMig/Controllers/ZoneController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using PagedList.Mvc;
using PagedList;
using System.Web.Mvc;
using WorkFlowaMig.Models;

namespace WorkFlowaMig.Controllers
{
    public class ZoneController : Controller
    {
        private WorkflowEntities _context;

        //Constructeur 

        public ZoneController()
        {
            _context = new WorkflowEntities();
        }
        // GET: /Zone/
        public ActionResult Index(string search, string sort, int? page)
        {
            IQueryable<Zone> zones = _context.Zones;

            if (!String.IsNullOrWhiteSpace(sort))
            {
                if (sort == "ZoneId_ASC")
                    zones = zones.OrderBy(c => c.Id);
                else if (sort == "ZoneId_DESC")
                    zones = zones.OrderByDescending(c => c.Id);

                else if (sort == "ZoneName_ASC")
                    zones = zones.OrderBy(c => c.Name);
                else if (sort == "ZoneName_DESC")
                    zones = zones.OrderByDescending(c => c.Name);
            }
            else
            {
                zones = zones.OrderByDescending(c => c.Id);
            }
            ViewBag.CurrentSort = sort;

            if (!String.IsNullOrWhiteSpace(search))
            {
                ViewBag.CurrentSearch = search;
                zones = zones.Where(c => c.Name.Contains(search));
            }
            //zones = zones.OrderByDescending(c => c.Id);
            int pageSize = 6;
            int pageNumber = page ?? 1;
          return PartialView(zones.ToPagedList(pageNumber, pageSize));

        }

        //Get all zones in db 

        public ActionResult GetZones()
        {
            var _zoneList = _context.Zones.ToList();
            return Json(_zoneList, JsonRequestBehavior.AllowGet);
        }

        //Get Zone By Id

        public ActionResult GetZone(int id)
        {
            var _zone = _context.Zones.Where(z => z.Id == id).FirstOrDefault();
            return Json(_zone, JsonRequestBehavior.AllowGet);
        }

        // Add zone 
        [HttpPost]
        public ActionResult AddZone([Bind(Exclude="Id")]Zone zone)
        {
            if(ModelState.IsValid)
            {
                _context.Zones.Add(zone);
                _context.SaveChanges();
               
            }
            return Json(zone, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Update(Zone zone)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(zone).State = EntityState.Modified;
                _context.SaveChanges();
            }

            return Json(zone, JsonRequestBehavior.AllowGet);
        }

       
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var zone = _context.Zones.ToList().Find(m => m.Id == id);
            if (zone != null)
            {
                _context.Zones.Remove(zone);
                _context.SaveChanges();
            }

            return Json(zone, JsonRequestBehavior.AllowGet);
        }

	}
}

WorkFlowaMig/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")

</head>
<body>
    <table width="1150px;" align="center">
        <tr style="background-color:darkgreen">
            <td>
                <div class="navbar navbar-default">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            @*@Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })*@
                            <img src="~/Content/Images/Amen.png" class="img img-responsive" width="150px" height="100px" />

                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li>&nbsp;&nbsp;</li>
                                <li>@Html.ActionLink("Zones", "Index", "Zone")</li>
                                <li>@Html.ActionLink("Agences", "Index", "Agence")</li>
                                <li>@Html.ActionLink("Documents", "Index", "Document")</li>
                                <li>@Html.ActionLink("Sacs", "Index", "Home")</li>
                                <li>@Html.ActionLink("JC", "About", "Home")</li>
                                <li>@Html.ActionLink("Statistiques", "Contact", "Home")</li>
                            </ul>
                            @Html.Partial("_LoginPartial")
                        </div>
                    </div>
                </div>
            </td>
        </tr>

    </table>
   
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>